// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAvESe1FZ97f21Vjp04dPyM7w9AWRd2OQ',
    appId: '1:613654372592:web:bbc2cd8e7ccf64a6f2e235',
    messagingSenderId: '613654372592',
    projectId: 'todo-7a4f6',
    authDomain: 'todo-7a4f6.firebaseapp.com',
    storageBucket: 'todo-7a4f6.firebasestorage.app',
    measurementId: 'G-ZYZCM7N5BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMyZ-2TKtVve9XExQYIMJ4HlO2qaWRY24',
    appId: '1:613654372592:android:7b8df402637f9979f2e235',
    messagingSenderId: '613654372592',
    projectId: 'todo-7a4f6',
    storageBucket: 'todo-7a4f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCmpfOq0P4jQwPkPiZf8IHgDZv61Iteto',
    appId: '1:613654372592:ios:6596aa8d486695ebf2e235',
    messagingSenderId: '613654372592',
    projectId: 'todo-7a4f6',
    storageBucket: 'todo-7a4f6.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCmpfOq0P4jQwPkPiZf8IHgDZv61Iteto',
    appId: '1:613654372592:ios:6596aa8d486695ebf2e235',
    messagingSenderId: '613654372592',
    projectId: 'todo-7a4f6',
    storageBucket: 'todo-7a4f6.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAvESe1FZ97f21Vjp04dPyM7w9AWRd2OQ',
    appId: '1:613654372592:web:f22c23bec798847af2e235',
    messagingSenderId: '613654372592',
    projectId: 'todo-7a4f6',
    authDomain: 'todo-7a4f6.firebaseapp.com',
    storageBucket: 'todo-7a4f6.firebasestorage.app',
    measurementId: 'G-P5RHMPPXDS',
  );
}
